# GitHub Actions
# https://help.github.com/en/articles/configuring-a-workflow
name: Release tests

on: push

jobs:
    test1:
        name: Release tests
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@master

            # install a specific version of Node using
            # https://github.com/actions/setup-node
            - name: Use Node.js v16
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            # just so we learn about available environment variables GitHub provides
            - name: Print env variables
              run: |
                  npm i -g @bahmutov/print-env
                  print-env GITHUB

            # Restore the previous NPM modules and Cypress binary archives.
            # Any updated archives will be saved automatically after the entire
            # workflow successfully finishes.
            # See https://github.com/actions/cache
            - name: Cache node modules
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Cache Cypress binary
              uses: actions/cache@v1
              with:
                  path: ~/.cache/Cypress
                  key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      cypress-${{ runner.os }}-cypress-

            - name: install dependencies and verify Cypress
              env:
                  # make sure every Cypress install prints minimal information
                  CI: 1
              # print Cypress and OS info
              run: |
                  npm ci
                  npx cypress verify
                  npx cypress info
                  npx cypress version
                  npx cypress version --component package
                  npx cypress version --component binary
                  npx cypress version --component electron
                  npx cypress version --component node

            # Runs Cypress tests using the parallel spec runner
            - name: Release tests
              run: npm run release-test
              env:
                  TERM: xterm
                  UA_SUFFIX: ${{ secrets.UA_SUFFIX }}
              timeout-minutes: 20

            # https://github.com/actions/upload-artifact
            - name: Upload test-reports
              if: always()
              uses: actions/upload-artifact@master
              with:
                  name: test-reports
                  path: test-reports

            - name: Upload mochawesome report
              if: always()
              uses: actions/upload-artifact@master
              with:
                  name: mochawesome
                  path: test-reports/mochawesome.html
